#************************** DADAprep v.1.0 config file ************************#

#********** MIT LICENSE - Copyright © 2022 Gian M.N. Benucci, Ph.D. ***********#
#*********************** email: benucci[at]msu[dot]edu ************************#

#************* ALL THE FIELDS BELOW MUST BE SELECTED BY THE USER **************#
#==============================================================================#
project_dir="/mnt/home/benucci/DADA2_pipeline"

# Change your MSUusername based on MSU ID 
MSUusername="benucci"

# Phix indexed database
phix_db="/mnt/research/ShadeLab/Benucci/databases/phix_index/my_phix"

# R1 and R2 with identical number of sequences
paired="yes"

# Selected PCR primers
fwd_primer="CCTACGGGAGGCAGCAG" # 341F fwd primer (Albersten et al., PLoS ONE. 2015;10:e0132783)
rev_primer="GGACTACHVGGGTWTCTAAT" # 806R rev primer (Apprill et al., 2015. modified by Caporaso)

#****************************** END OF USER INPUT ****************************#
#=============================================================================#

